//using System;
//using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;

//namespace HarmonyHaven.Models
//{
//    public class User
//    {
//        public int UserID { get; set; } // Automatically generated by the database

//        [Required]
//        public string Username { get; set; }

//        [Required]
//        [EmailAddress]
//        [MaxLength(256)]
//        public string Email { get; set; } // Unique constraint added here

//        [Required]
//        public string Password { get; set; }

//        [NotMapped] // Not mapped to database
//        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
//        public string ConfirmPassword { get; set; }

//        public string ResetToken { get; set; }
//        public DateTime? ResetTokenExpiryDate { get; set; }

//        public DateTime RegistrationDate { get; set; } 
//        [NotMapped]
//        public string NormalizedUserName => Username.ToUpperInvariant();

//        public void SetUsername(string newUsername)
//        {
//            Username = newUsername;
//        }

//        // Konstruktor
//        public User()
//        {
//            RegistrationDate = DateTime.Now;
//        }
//    }

//}

